openapi: 3.0.1
info:
  title: XSLT_API
  description: API Definition of XSLT_API
  version: 1.0.0
servers:
- url: http://localhost:8290/sample
paths:
  /:
    post:
      responses:
        default:
          description: Default response
